[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
rumqttc = {git = "https://github.com/bytebeamio/rumqtt.git"}
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.5", features = ["ws", "headers"] }
tracing-subscriber = { version="0.3", features = ["env-filter"] }
tower-http = { version = "0.2.0", features = ["fs", "trace"] }
serde = { version = "1.0", features = ["derive"] }
bonsaidb = { version = "0.4", features = ["local-full"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
bytes = "1.1.0"
prost = "0.9"
anyhow = "1.0"
once_cell = "1.12.0"
thiserror = "1.0.31"
futures = "0.3.21"
async-trait = "0.1.52"
rand = "0.8.5"
dashmap = "5.3.4"
flume = "0.10.13"