// @generated by protobuf-ts 2.4.0 with parameter client_none,// @generated from protobuf file "protocol.proto" (package "protocol", syntax proto3),// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message protocol.Void
 */
export interface Void {
}
/**
 * @generated from protobuf message protocol.Sensor
 */
export interface Sensor {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
}
/**
 * @generated from protobuf message protocol.SensorValue
 */
export interface SensorValue {
    /**
     * @generated from protobuf field: float value = 1;
     */
    value: number;
}
/**
 * @generated from protobuf message protocol.Zigbee2MQTTConfig
 */
export interface Zigbee2MQTTConfig {
    /**
     * @generated from protobuf field: string url = 1;
     */
    url: string;
    /**
     * @generated from protobuf field: string username = 2;
     */
    username: string;
    /**
     * @generated from protobuf field: string password = 3;
     */
    password: string;
}
/**
 * @generated from protobuf message protocol.Zigbee2MQTTStats
 */
export interface Zigbee2MQTTStats {
    /**
     * @generated from protobuf field: int32 sources = 1;
     */
    sources: number;
    /**
     * @generated from protobuf field: int32 sinks = 2;
     */
    sinks: number;
    /**
     * @generated from protobuf field: int32 sourcesinks = 3;
     */
    sourcesinks: number;
    /**
     * @generated from protobuf field: int32 devices = 4;
     */
    devices: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class Void$Type extends MessageType<Void> {
    constructor() {
        super("protocol.Void", []);
    }
    create(value?: PartialMessage<Void>): Void {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Void>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Void): Void {
        return target ?? this.create();
    }
    internalBinaryWrite(message: Void, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message protocol.Void
 */
export const Void = new Void$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Sensor$Type extends MessageType<Sensor> {
    constructor() {
        super("protocol.Sensor", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Sensor>): Sensor {
        const message = { id: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Sensor>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Sensor): Sensor {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Sensor, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message protocol.Sensor
 */
export const Sensor = new Sensor$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SensorValue$Type extends MessageType<SensorValue> {
    constructor() {
        super("protocol.SensorValue", [
            { no: 1, name: "value", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<SensorValue>): SensorValue {
        const message = { value: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<SensorValue>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SensorValue): SensorValue {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* float value */ 1:
                    message.value = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SensorValue, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* float value = 1; */
        if (message.value !== 0)
            writer.tag(1, WireType.Bit32).float(message.value);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message protocol.SensorValue
 */
export const SensorValue = new SensorValue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Zigbee2MQTTConfig$Type extends MessageType<Zigbee2MQTTConfig> {
    constructor() {
        super("protocol.Zigbee2MQTTConfig", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Zigbee2MQTTConfig>): Zigbee2MQTTConfig {
        const message = { url: "", username: "", password: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Zigbee2MQTTConfig>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Zigbee2MQTTConfig): Zigbee2MQTTConfig {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string url */ 1:
                    message.url = reader.string();
                    break;
                case /* string username */ 2:
                    message.username = reader.string();
                    break;
                case /* string password */ 3:
                    message.password = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Zigbee2MQTTConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string url = 1; */
        if (message.url !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.url);
        /* string username = 2; */
        if (message.username !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.username);
        /* string password = 3; */
        if (message.password !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.password);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message protocol.Zigbee2MQTTConfig
 */
export const Zigbee2MQTTConfig = new Zigbee2MQTTConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Zigbee2MQTTStats$Type extends MessageType<Zigbee2MQTTStats> {
    constructor() {
        super("protocol.Zigbee2MQTTStats", [
            { no: 1, name: "sources", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "sinks", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "sourcesinks", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "devices", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Zigbee2MQTTStats>): Zigbee2MQTTStats {
        const message = { sources: 0, sinks: 0, sourcesinks: 0, devices: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Zigbee2MQTTStats>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Zigbee2MQTTStats): Zigbee2MQTTStats {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 sources */ 1:
                    message.sources = reader.int32();
                    break;
                case /* int32 sinks */ 2:
                    message.sinks = reader.int32();
                    break;
                case /* int32 sourcesinks */ 3:
                    message.sourcesinks = reader.int32();
                    break;
                case /* int32 devices */ 4:
                    message.devices = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Zigbee2MQTTStats, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 sources = 1; */
        if (message.sources !== 0)
            writer.tag(1, WireType.Varint).int32(message.sources);
        /* int32 sinks = 2; */
        if (message.sinks !== 0)
            writer.tag(2, WireType.Varint).int32(message.sinks);
        /* int32 sourcesinks = 3; */
        if (message.sourcesinks !== 0)
            writer.tag(3, WireType.Varint).int32(message.sourcesinks);
        /* int32 devices = 4; */
        if (message.devices !== 0)
            writer.tag(4, WireType.Varint).int32(message.devices);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message protocol.Zigbee2MQTTStats
 */
export const Zigbee2MQTTStats = new Zigbee2MQTTStats$Type();
/**
 * @generated ServiceType for protobuf service protocol.Zigbee2MQTTService
 */
export const Zigbee2MQTTService = new ServiceType("protocol.Zigbee2MQTTService", [
    { name: "Config", options: {}, I: Zigbee2MQTTConfig, O: Zigbee2MQTTStats },
    { name: "Status", options: {}, I: Void, O: Zigbee2MQTTStats }
]);
/**
 * @generated ServiceType for protobuf service protocol.StatisticsService
 */
export const StatisticsService = new ServiceType("protocol.StatisticsService", [
    { name: "Listen", serverStreaming: true, options: {}, I: Sensor, O: SensorValue }
]);
import { derived, type Readable } from "svelte/store";

export interface RpcTransport {
    unary(serviceId: number, callId: number, input: Uint8Array): Promise<Uint8Array>;
    stream(serviceId: number, callId: number, input: Uint8Array): Readable<Uint8Array>;
}
// ========================== Zigbee2MqttService ==========================
export class Zigbee2MqttServiceClient {
    constructor(private transport: RpcTransport) {}

    
        
            config(input: Zigbee2MQTTConfig): Promise<Zigbee2MQTTStats> {
                return this.transport.unary(
                    0xd109,
                    0xd74e,
                    Zigbee2MQTTConfig.toBinary(input),
                ).then(b => b ? Zigbee2MQTTStats.fromBinary(b) : null);
            }
        
    
        
            status(input: Void): Promise<Zigbee2MQTTStats> {
                return this.transport.unary(
                    0xd109,
                    0x9b83,
                    Void.toBinary(input),
                ).then(b => b ? Zigbee2MQTTStats.fromBinary(b) : null);
            }
        
    
}
// ========================== StatisticsService ==========================
export class StatisticsServiceClient {
    constructor(private transport: RpcTransport) {}

    
        
            listen(input: Sensor): Readable<SensorValue> {
                return derived( 
                    this.transport.stream(
                        0x5f00,
                        0x47a5, 
                        Sensor.toBinary(input)
                    ), 
                    b => b ? SensorValue.fromBinary(b) : null
                );
            }
        
    
}
